"""Initial schema

Revision ID: 0001
Revises:
Create Date: 2026-06-10
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("users",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("email", sa.String, nullable=False, unique=True),
        sa.Column("full_name", sa.String, nullable=False),
        sa.Column("persona_key", sa.String, nullable=False),
        sa.Column("hashed_password", sa.String, nullable=False),
        sa.Column("is_active", sa.Boolean, default=True),
        sa.Column("job_title", sa.String),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table("journey_stages",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("stage_key", sa.String, nullable=False, unique=True),
        sa.Column("day_label", sa.String, nullable=False),
        sa.Column("type", sa.String, nullable=False),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("time_description", sa.String),
        sa.Column("sla_hours", sa.Float),
        sa.Column("sequence_order", sa.Integer, nullable=False),
        sa.Column("is_branch_point", sa.Boolean, default=False),
        sa.Column("is_light_path_skip", sa.Boolean, default=False),
        sa.Column("meeting_chair_persona", sa.String),
        sa.Column("meeting_attendees_personas", postgresql.JSON),
        sa.Column("what", sa.String),
        sa.Column("when_condition", sa.String),
        sa.Column("include_items", sa.String),
    )

    op.create_table("rasci_matrix",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("stage_key", sa.String, nullable=False),
        sa.Column("persona_key", sa.String, nullable=False),
        sa.Column("rasci_code", sa.String, nullable=False),
    )

    op.create_table("airlines",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("iata_code", sa.String),
        sa.Column("type", sa.String, nullable=False),
        sa.Column("hq_country", sa.String, nullable=False),
        sa.Column("other_countries_operated", postgresql.JSON, default=list),
        sa.Column("uk_airports_served", postgresql.JSON, default=list),
        sa.Column("estimated_annual_spend_gbp_m", sa.Float),
        sa.Column("estimated_next_review_date", sa.Date),
        sa.Column("notes", sa.Text),
        sa.Column("is_illustrative", sa.Boolean, default=True),
        sa.Column("is_dcuk_customer", sa.Boolean, default=False),
    )

    op.create_table("airport_presence",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("airline_id", sa.Integer, sa.ForeignKey("airlines.id"), nullable=False),
        sa.Column("airport_code", sa.String, nullable=False),
        sa.Column("current_caterer", sa.String, nullable=False),
        sa.Column("is_dcuk", sa.Boolean, default=False),
    )

    op.create_table("tenders",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_ref", sa.String, nullable=False, unique=True),
        sa.Column("airline_id", sa.Integer, sa.ForeignKey("airlines.id")),
        sa.Column("customer_name", sa.String, nullable=False),
        sa.Column("received_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("customer_deadline", sa.DateTime(timezone=True)),
        sa.Column("submission_format", sa.String),
        sa.Column("current_stage_key", sa.String, nullable=False, default="receive_tender"),
        sa.Column("current_owner_persona", sa.String),
        sa.Column("branch", sa.String),
        sa.Column("status", sa.String, nullable=False, default="active"),
        sa.Column("estimated_contract_value_gbp", sa.Float),
        sa.Column("is_renewal", sa.Boolean, default=False),
        sa.Column("response_posture", sa.String),
        sa.Column("atria_upload_path", sa.String),
        sa.Column("atria_raw_json", postgresql.JSON),
        sa.Column("scope_summary", sa.Text),
        sa.Column("created_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("stage_entered_at", sa.DateTime(timezone=True)),
        sa.Column("et_sla_deadline", sa.DateTime(timezone=True)),
    )

    op.create_table("tender_audit_entries",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("stage_key", sa.String, nullable=False),
        sa.Column("actor_user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("actor_name", sa.String, nullable=False),
        sa.Column("rasci_capacity", sa.String, nullable=False),
        sa.Column("action", sa.String, nullable=False),
        sa.Column("before_state", postgresql.JSON),
        sa.Column("after_state", postgresql.JSON),
        sa.Column("comment", sa.Text),
    )

    op.create_table("tender_versions",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), nullable=False),
        sa.Column("version_number", sa.Integer, nullable=False),
        sa.Column("created_by", sa.Integer, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("model_inputs", postgresql.JSON),
        sa.Column("model_outputs", postgresql.JSON),
        sa.Column("is_illustrative", sa.Boolean, default=True),
    )

    op.create_table("financial_models",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), unique=True, nullable=False),
        sa.Column("annual_flights", sa.Integer),
        sa.Column("avg_pax_per_flight", sa.Integer),
        sa.Column("aircraft_type_mix", postgresql.JSON),
        sa.Column("fb_cost_per_pax", sa.Float),
        sa.Column("non_fb_cost_per_flight", sa.Float),
        sa.Column("operational_availability_pct", sa.Float),
        sa.Column("ramp_variability_pct", sa.Float),
        sa.Column("margin_target_pct", sa.Float),
        sa.Column("total_annual_cost", sa.Float),
        sa.Column("total_annual_price", sa.Float),
        sa.Column("gross_margin_gbp", sa.Float),
        sa.Column("gross_margin_pct", sa.Float),
        sa.Column("sensitivity_table", postgresql.JSON),
        sa.Column("version_number", sa.Integer, default=1),
        sa.Column("last_saved_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("last_saved_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("is_illustrative", sa.Boolean, default=True),
    )

    op.create_table("capture_plans",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), unique=True, nullable=False),
        sa.Column("customer_brief", sa.Text),
        sa.Column("why_in_market", sa.Text),
        sa.Column("key_dates", postgresql.JSON),
        sa.Column("response_posture", sa.String),
        sa.Column("initial_financial_summary", sa.Text),
        sa.Column("decisions_to_take", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table("strategy_meetings",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), unique=True, nullable=False),
        sa.Column("held_at", sa.DateTime(timezone=True)),
        sa.Column("attendees", postgresql.JSON, default=list),
        sa.Column("floor_gbp", sa.Float),
        sa.Column("floor_margin_pct", sa.Float),
        sa.Column("pricing_parameters", postgresql.JSON),
        sa.Column("response_posture", sa.String),
        sa.Column("decisions", postgresql.JSON, default=list),
        sa.Column("created_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table("dtp_packs",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), unique=True, nullable=False),
        sa.Column("opportunity_intro", sa.Text),
        sa.Column("key_metrics", postgresql.JSON),
        sa.Column("win_strategy", sa.Text),
        sa.Column("model_sense_check", sa.Text),
        sa.Column("recommendation", sa.String),
        sa.Column("submitted_at", sa.DateTime(timezone=True)),
        sa.Column("et_sla_deadline", sa.DateTime(timezone=True)),
        sa.Column("created_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table("et_decisions",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), nullable=False),
        sa.Column("stage_key", sa.String, nullable=False),
        sa.Column("decided_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("decided_by_name", sa.String),
        sa.Column("decision", sa.String),
        sa.Column("rationale", sa.Text),
        sa.Column("decided_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("is_delegated", sa.Boolean, default=False),
    )

    op.create_table("tender_deliverable_trackers",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), nullable=False),
        sa.Column("element_key", sa.String, nullable=False),
        sa.Column("element_name", sa.String, nullable=False),
        sa.Column("owner_user_id", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("owner_name", sa.String),
        sa.Column("due_date", sa.DateTime(timezone=True)),
        sa.Column("status", sa.String, default="pending"),
    )

    op.create_table("elements",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), nullable=False),
        sa.Column("element_key", sa.String, nullable=False),
        sa.Column("element_name", sa.String, nullable=False),
        sa.Column("status", sa.String, default="prepare"),
        sa.Column("owner_user_id", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("owner_name", sa.String),
        sa.Column("draft_content", postgresql.JSON),
        sa.Column("version_number", sa.Integer, default=1),
        sa.Column("submitted_at", sa.DateTime(timezone=True)),
        sa.Column("reviewed_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("reviewed_at", sa.DateTime(timezone=True)),
        sa.Column("review_comment", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table("element_exceptions",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("element_id", sa.Integer, sa.ForeignKey("elements.id"), nullable=False),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), nullable=False),
        sa.Column("exception_type", sa.String, nullable=False),
        sa.Column("raised_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("raised_by_name", sa.String),
        sa.Column("raised_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("evidence_notes", sa.Text),
        sa.Column("routed_to", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("status", sa.String, default="open"),
        sa.Column("resolved_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("resolved_at", sa.DateTime(timezone=True)),
        sa.Column("resolution_comment", sa.Text),
    )

    op.create_table("mpls",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), nullable=False),
        sa.Column("version_number", sa.Integer, default=1),
        sa.Column("status", sa.String, default="draft"),
        sa.Column("line_items", postgresql.JSON, default=list),
        sa.Column("total_cost", sa.Float),
        sa.Column("total_price", sa.Float),
        sa.Column("margin_pct", sa.Float),
        sa.Column("approved_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("approved_by_name", sa.String),
        sa.Column("approved_at", sa.DateTime(timezone=True)),
        sa.Column("rejection_comment", sa.Text),
        sa.Column("created_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("is_illustrative", sa.Boolean, default=True),
    )

    op.create_table("submission_packs",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), unique=True, nullable=False),
        sa.Column("collated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("collated_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("element_versions", postgresql.JSON),
        sa.Column("mpl_id", sa.Integer, sa.ForeignKey("mpls.id")),
        sa.Column("financial_model_version", sa.Integer),
        sa.Column("gaps_detected", postgresql.JSON),
        sa.Column("readiness_signed_off_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("readiness_signed_off_at", sa.DateTime(timezone=True)),
        sa.Column("variance_flags", postgresql.JSON),
    )

    op.create_table("co_approvals",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), unique=True, nullable=False),
        sa.Column("sales_director_user_id", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("sd_approved_at", sa.DateTime(timezone=True)),
        sa.Column("finance_director_user_id", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("fd_approved_at", sa.DateTime(timezone=True)),
        sa.Column("status", sa.String, default="pending"),
    )

    op.create_table("et_approval_meetings",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), unique=True, nullable=False),
        sa.Column("held_at", sa.DateTime(timezone=True)),
        sa.Column("chair_user_id", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("attendees", postgresql.JSON, default=list),
        sa.Column("decisions_per_approver", postgresql.JSON, default=list),
        sa.Column("outcome", sa.String),
        sa.Column("outcome_at", sa.DateTime(timezone=True)),
    )

    op.create_table("submission_records",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), unique=True, nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("submitted_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("submitted_by_name", sa.String),
        sa.Column("format", sa.String),
        sa.Column("access_method", sa.String),
        sa.Column("what_was_sent", sa.Text),
        sa.Column("what_was_requested", sa.Text),
    )

    op.create_table("post_submission_records",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("tender_id", sa.Integer, sa.ForeignKey("tenders.id"), nullable=False),
        sa.Column("record_type", sa.String),
        sa.Column("notes", sa.Text),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("participants", postgresql.JSON, default=list),
        sa.Column("updated_by", sa.Integer, sa.ForeignKey("users.id")),
    )

    op.create_table("rate_cards",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("category", sa.String, nullable=False),
        sa.Column("line_item_name", sa.String, nullable=False),
        sa.Column("description", sa.Text),
        sa.Column("cost_gbp", sa.Float, nullable=False),
        sa.Column("unit", sa.String, default="per_item"),
        sa.Column("effective_from", sa.Date, nullable=False),
        sa.Column("effective_to", sa.Date),
        sa.Column("is_illustrative", sa.Boolean, default=True),
    )

    op.create_table("apl_items",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("product_name", sa.String, nullable=False),
        sa.Column("category", sa.String, nullable=False),
        sa.Column("sub_category", sa.String),
        sa.Column("supplier", sa.String, nullable=False),
        sa.Column("agreed_price_gbp", sa.Float, nullable=False),
        sa.Column("unit", sa.String, default="per_item"),
        sa.Column("effective_from", sa.Date, nullable=False),
        sa.Column("effective_to", sa.Date),
        sa.Column("status", sa.String, default="active"),
        sa.Column("is_illustrative", sa.Boolean, default=True),
    )

    op.create_table("recipes",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("category", sa.String, nullable=False),
        sa.Column("cabin_class", sa.String),
        sa.Column("ingredients", postgresql.JSON, default=list),
        sa.Column("calculated_cost_gbp", sa.Float),
        sa.Column("last_reviewed_date", sa.Date),
        sa.Column("is_illustrative", sa.Boolean, default=True),
    )

    op.create_table("pricing_guidelines",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("effective_from", sa.Date, nullable=False),
        sa.Column("min_margin_pct", sa.Float, nullable=False),
        sa.Column("target_margin_pct", sa.Float, nullable=False),
        sa.Column("floor_formula_description", sa.Text),
        sa.Column("exception_threshold_gbp", sa.Float),
        sa.Column("updated_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("is_illustrative", sa.Boolean, default=True),
    )

    op.create_table("app_settings",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("key", sa.String, unique=True, nullable=False),
        sa.Column("value", postgresql.JSON, nullable=False),
        sa.Column("description", sa.Text),
        sa.Column("category", sa.String, default="general"),
        sa.Column("updated_by", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("updated_by_name", sa.String),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table("historical_tenders",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("customer_name", sa.String, nullable=False),
        sa.Column("airline_type", sa.String),
        sa.Column("contract_value_gbp", sa.Float),
        sa.Column("submission_date", sa.Date),
        sa.Column("outcome_date", sa.Date),
        sa.Column("outcome", sa.String),
        sa.Column("lost_stage", sa.String),
        sa.Column("won_lost_reason", sa.Text),
        sa.Column("contract_length_years", sa.Float),
        sa.Column("airports_covered", sa.String),
        sa.Column("is_historical", sa.Boolean, default=True),
        sa.Column("is_illustrative", sa.Boolean, default=True),
    )


def downgrade() -> None:
    for table in [
        "historical_tenders", "app_settings", "pricing_guidelines", "recipes",
        "apl_items", "rate_cards", "post_submission_records", "submission_records",
        "et_approval_meetings", "co_approvals", "submission_packs", "mpls",
        "element_exceptions", "elements", "tender_deliverable_trackers", "et_decisions",
        "dtp_packs", "strategy_meetings", "capture_plans", "financial_models",
        "tender_versions", "tender_audit_entries", "tenders",
        "airport_presence", "airlines", "rasci_matrix", "journey_stages", "users",
    ]:
        op.drop_table(table)
