"""Seed 40 illustrative airlines. Idempotent."""
from datetime import date

AIRLINES = [
    {"name": "Emerald Skies", "iata_code": "ES", "type": "full_service", "hq_country": "United Kingdom",
     "uk_airports_served": ["LHR", "LGW", "MAN"], "other_countries_operated": ["UAE", "USA", "Singapore"],
     "estimated_annual_spend_gbp_m": 4.2, "estimated_next_review_date": date(2026, 9, 1),
     "is_dcuk_customer": True, "notes": "Long-standing dCUK customer. Re-tender expected Q3 2026."},
    {"name": "Crescent Air", "iata_code": "CA", "type": "full_service", "hq_country": "Qatar",
     "uk_airports_served": ["LHR", "MAN"], "other_countries_operated": ["Qatar", "UAE", "Germany", "France"],
     "estimated_annual_spend_gbp_m": 6.8, "estimated_next_review_date": date(2026, 11, 15),
     "is_dcuk_customer": False, "notes": "Currently catered by Gate Gourmet at LHR. Strategic target."},
    {"name": "Polar Atlantic", "iata_code": "PA", "type": "full_service", "hq_country": "Norway",
     "uk_airports_served": ["LHR", "EDI", "MAN"], "other_countries_operated": ["Norway", "Sweden", "Denmark", "USA"],
     "estimated_annual_spend_gbp_m": 3.1, "estimated_next_review_date": date(2026, 8, 30),
     "is_dcuk_customer": True, "notes": "Premium cabin contract under review. Strong incumbent position."},
    {"name": "Meridian Express", "iata_code": "MX", "type": "full_service", "hq_country": "United Arab Emirates",
     "uk_airports_served": ["LHR", "LGW", "BHX", "MAN"], "other_countries_operated": ["UAE", "India", "Singapore", "Australia"],
     "estimated_annual_spend_gbp_m": 8.5, "estimated_next_review_date": date(2026, 10, 1),
     "is_dcuk_customer": False, "notes": "High-value target. Currently dnata Group catering in UAE — leverage group relationship."},
    {"name": "Highland Carrier", "iata_code": "HC", "type": "charter", "hq_country": "United Kingdom",
     "uk_airports_served": ["EDI", "GLA", "MAN", "BFS"], "other_countries_operated": ["Spain", "Greece", "Turkey"],
     "estimated_annual_spend_gbp_m": 1.4, "estimated_next_review_date": date(2026, 7, 15),
     "is_dcuk_customer": True, "notes": "Charter carrier. Seasonal peaks. Renewal imminent."},
    {"name": "Aurora Air", "iata_code": "AA", "type": "full_service", "hq_country": "Canada",
     "uk_airports_served": ["LHR", "MAN"], "other_countries_operated": ["Canada", "USA", "France"],
     "estimated_annual_spend_gbp_m": 2.8, "estimated_next_review_date": date(2027, 2, 1),
     "is_dcuk_customer": False, "notes": "New route launch LHR–Toronto. Competitor (LSG) currently holds contract."},
    {"name": "Cobalt Airlines", "iata_code": "CB", "type": "low_cost", "hq_country": "United Kingdom",
     "uk_airports_served": ["LGW", "STN", "LTN", "BHX"], "other_countries_operated": ["Spain", "Portugal", "Greece", "Italy"],
     "estimated_annual_spend_gbp_m": 3.6, "estimated_next_review_date": date(2026, 12, 1),
     "is_dcuk_customer": True, "notes": "Major UK LCC. Major renewal in progress."},
    {"name": "Saffron Express", "iata_code": "SX", "type": "full_service", "hq_country": "India",
     "uk_airports_served": ["LHR", "BHX"], "other_countries_operated": ["India", "UAE", "Singapore"],
     "estimated_annual_spend_gbp_m": 2.2, "estimated_next_review_date": date(2026, 6, 30),
     "is_dcuk_customer": True, "notes": "Submission just completed Day 12."},
    {"name": "Vantage Air", "iata_code": "VA", "type": "full_service", "hq_country": "Germany",
     "uk_airports_served": ["LHR", "MAN", "EDI"], "other_countries_operated": ["Germany", "France", "Italy", "USA"],
     "estimated_annual_spend_gbp_m": 5.1, "estimated_next_review_date": date(2027, 3, 1),
     "is_dcuk_customer": False, "notes": "Gate Gourmet incumbent. Group presence in Germany — opportunity."},
    {"name": "Strata Pacific", "iata_code": "SP", "type": "full_service", "hq_country": "Australia",
     "uk_airports_served": ["LHR"], "other_countries_operated": ["Australia", "Singapore", "UAE", "Japan"],
     "estimated_annual_spend_gbp_m": 4.7, "estimated_next_review_date": date(2027, 6, 1),
     "is_dcuk_customer": False, "notes": "Premium long-haul. dnata Group catering in Singapore and UAE."},
    {"name": "Cascade Blue", "iata_code": "CZ", "type": "low_cost", "hq_country": "United Kingdom",
     "uk_airports_served": ["STN", "LTN", "EMA", "BRS"], "other_countries_operated": ["Spain", "France", "Poland"],
     "estimated_annual_spend_gbp_m": 1.8, "estimated_next_review_date": date(2026, 11, 1),
     "is_dcuk_customer": False, "notes": "Buy-on-board model. Currently self-catering. Exploring outsource."},
    {"name": "Solstice Airways", "iata_code": "SO", "type": "charter", "hq_country": "United Kingdom",
     "uk_airports_served": ["MAN", "BHX", "NCL", "LPL"], "other_countries_operated": ["Spain", "Greece", "Cyprus", "Mexico"],
     "estimated_annual_spend_gbp_m": 1.1, "estimated_next_review_date": date(2026, 8, 1),
     "is_dcuk_customer": True, "notes": "Seasonal charter. Peak summer demand."},
    {"name": "Thornwick Air", "iata_code": "TA", "type": "low_cost", "hq_country": "Ireland",
     "uk_airports_served": ["STN", "LTN", "BFS", "EDI", "GLA"], "other_countries_operated": ["Ireland", "Spain", "Portugal", "Italy"],
     "estimated_annual_spend_gbp_m": 2.4, "estimated_next_review_date": date(2027, 1, 1),
     "is_dcuk_customer": False, "notes": "Large LCC. Crew meals only at present. Expansion possible."},
    {"name": "Marlowe Aviation", "iata_code": "MW", "type": "full_service", "hq_country": "United Kingdom",
     "uk_airports_served": ["LHR", "LGW"], "other_countries_operated": ["USA", "Canada", "Jamaica"],
     "estimated_annual_spend_gbp_m": 3.9, "estimated_next_review_date": date(2026, 9, 30),
     "is_dcuk_customer": True, "notes": "Transatlantic specialist. Premium cabin focus."},
    {"name": "Indigo Route", "iata_code": "IR", "type": "low_cost", "hq_country": "Netherlands",
     "uk_airports_served": ["LGW", "STN", "BRS"], "other_countries_operated": ["Netherlands", "Germany", "Spain", "France"],
     "estimated_annual_spend_gbp_m": 1.6, "estimated_next_review_date": date(2027, 4, 1),
     "is_dcuk_customer": False, "notes": "European LCC. Buy-on-board only. Gate Gourmet."},
    {"name": "Fenwick Skies", "iata_code": "FS", "type": "charter", "hq_country": "United Kingdom",
     "uk_airports_served": ["BRS", "CWL", "NCL"], "other_countries_operated": ["Spain", "Portugal", "Canaries"],
     "estimated_annual_spend_gbp_m": 0.7, "estimated_next_review_date": date(2026, 7, 1),
     "is_dcuk_customer": False, "notes": "Small regional charter. Competitor holds contract."},
    {"name": "Hadrian Global", "iata_code": "HG", "type": "full_service", "hq_country": "United Kingdom",
     "uk_airports_served": ["LHR", "EDI", "MAN", "NCL"], "other_countries_operated": ["UAE", "India", "Hong Kong", "Japan"],
     "estimated_annual_spend_gbp_m": 7.2, "estimated_next_review_date": date(2027, 5, 1),
     "is_dcuk_customer": True, "notes": "Major full-service UK carrier. Strategic partnership."},
    {"name": "Lakeshore Air", "iata_code": "LA", "type": "low_cost", "hq_country": "United Kingdom",
     "uk_airports_served": ["BHX", "EMA", "LPL", "NCL"], "other_countries_operated": [],
     "other_countries_operated": ["Spain", "Greece", "Turkey", "Portugal"],
     "estimated_annual_spend_gbp_m": 1.3, "estimated_next_review_date": date(2026, 10, 15),
     "is_dcuk_customer": False, "notes": "Growing regional LCC. Catered by Alpha LSG currently."},
    {"name": "Vesper Airways", "iata_code": "VW", "type": "full_service", "hq_country": "Singapore",
     "uk_airports_served": ["LHR"], "other_countries_operated": ["Singapore", "Australia", "Japan", "UAE"],
     "estimated_annual_spend_gbp_m": 5.8, "estimated_next_review_date": date(2027, 7, 1),
     "is_dcuk_customer": False, "notes": "Premium long-haul. dnata Group catering in Singapore — strong leverage."},
    {"name": "Redwood Airlines", "iata_code": "RW", "type": "full_service", "hq_country": "USA",
     "uk_airports_served": ["LHR", "MAN"], "other_countries_operated": ["USA", "Canada", "Mexico"],
     "estimated_annual_spend_gbp_m": 4.4, "estimated_next_review_date": date(2026, 12, 15),
     "is_dcuk_customer": False, "notes": "US major. dnata Group catering in JFK and LAX — cross-sell opportunity."},
    {"name": "Summit Express", "iata_code": "SE", "type": "low_cost", "hq_country": "Switzerland",
     "uk_airports_served": ["LGW", "LHR"], "other_countries_operated": ["Switzerland", "Austria", "Germany"],
     "estimated_annual_spend_gbp_m": 1.1, "estimated_next_review_date": date(2027, 2, 15),
     "is_dcuk_customer": False, "notes": "Swiss LCC. Crew meals + buy-on-board."},
    {"name": "Crest Pacific", "iata_code": "CP", "type": "charter", "hq_country": "United Kingdom",
     "uk_airports_served": ["MAN", "LGW", "BRS"], "other_countries_operated": ["Caribbean", "Mexico", "USA"],
     "estimated_annual_spend_gbp_m": 0.9, "estimated_next_review_date": date(2026, 10, 1),
     "is_dcuk_customer": True, "notes": "Long-haul charter. Specialist culinary requirements."},
    {"name": "Meridian Cargo", "iata_code": "MC", "type": "cargo", "hq_country": "United Arab Emirates",
     "uk_airports_served": ["LHR", "STN", "EMA"], "other_countries_operated": ["UAE", "India", "China"],
     "estimated_annual_spend_gbp_m": 0.4, "estimated_next_review_date": date(2027, 1, 15),
     "is_dcuk_customer": False, "notes": "Cargo only. Crew catering opportunity at LHR."},
    {"name": "Albatross Air", "iata_code": "AB", "type": "full_service", "hq_country": "South Africa",
     "uk_airports_served": ["LHR"], "other_countries_operated": ["South Africa", "Zimbabwe", "Kenya", "UAE"],
     "estimated_annual_spend_gbp_m": 2.0, "estimated_next_review_date": date(2027, 3, 15),
     "is_dcuk_customer": False, "notes": "Africa specialist. LSG incumbent at LHR."},
    {"name": "Clover Aviation", "iata_code": "CL", "type": "low_cost", "hq_country": "Ireland",
     "uk_airports_served": ["BFS", "EDI", "GLA", "BRS", "CWL"], "other_countries_operated": ["Ireland", "Spain", "Portugal"],
     "estimated_annual_spend_gbp_m": 0.8, "estimated_next_review_date": date(2026, 6, 20),
     "is_dcuk_customer": True, "notes": "Small LCC. Light-path renewal candidate."},
    {"name": "Saltire Air", "iata_code": "SA", "type": "charter", "hq_country": "United Kingdom",
     "uk_airports_served": ["EDI", "GLA", "ABZ"], "other_countries_operated": ["Spain", "Greece"],
     "estimated_annual_spend_gbp_m": 0.5, "estimated_next_review_date": date(2026, 9, 15),
     "is_dcuk_customer": True, "notes": "Scottish regional charter."},
    {"name": "Pennine Express", "iata_code": "PE", "type": "low_cost", "hq_country": "United Kingdom",
     "uk_airports_served": ["LPL", "NCL", "EMA", "MAN"], "other_countries_operated": ["Spain", "Portugal", "Greece"],
     "estimated_annual_spend_gbp_m": 1.0, "estimated_next_review_date": date(2027, 1, 30),
     "is_dcuk_customer": False, "notes": "Northern England LCC. Currently no contracted caterer."},
    {"name": "Severn Aviation", "iata_code": "SV", "type": "low_cost", "hq_country": "United Kingdom",
     "uk_airports_served": ["BRS", "CWL", "BHX"], "other_countries_operated": ["Spain", "France", "Ireland"],
     "estimated_annual_spend_gbp_m": 0.7, "estimated_next_review_date": date(2026, 11, 30),
     "is_dcuk_customer": False, "notes": "West of England LCC."},
    {"name": "Tyne Global", "iata_code": "TG", "type": "full_service", "hq_country": "United Kingdom",
     "uk_airports_served": ["NCL", "LHR", "MAN"], "other_countries_operated": ["USA", "Canada", "Caribbean"],
     "estimated_annual_spend_gbp_m": 2.6, "estimated_next_review_date": date(2027, 4, 15),
     "is_dcuk_customer": True, "notes": "North-East England full-service. Transatlantic routes."},
    {"name": "Kestrel Air", "iata_code": "KA", "type": "charter", "hq_country": "United Kingdom",
     "uk_airports_served": ["MAN", "BHX", "EMA", "LPL"], "other_countries_operated": ["Spain", "Turkey", "Egypt"],
     "estimated_annual_spend_gbp_m": 0.8, "estimated_next_review_date": date(2027, 5, 30),
     "is_dcuk_customer": False, "notes": "Midlands charter operator."},
    {"name": "Brunswick Airways", "iata_code": "BW", "type": "full_service", "hq_country": "Germany",
     "uk_airports_served": ["LHR", "MAN", "BHX"], "other_countries_operated": ["Germany", "Austria", "Switzerland", "USA"],
     "estimated_annual_spend_gbp_m": 5.4, "estimated_next_review_date": date(2027, 8, 1),
     "is_dcuk_customer": False, "notes": "German full-service. LSG Group catering in Germany."},
    {"name": "Montane Cargo", "iata_code": "MN", "type": "cargo", "hq_country": "United Kingdom",
     "uk_airports_served": ["LHR", "EMA", "STN"], "other_countries_operated": ["USA", "China", "UAE"],
     "estimated_annual_spend_gbp_m": 0.3, "estimated_next_review_date": date(2027, 2, 28),
     "is_dcuk_customer": False, "notes": "UK cargo. Small crew catering opportunity."},
    {"name": "Selbourne Air", "iata_code": "SL", "type": "low_cost", "hq_country": "United Kingdom",
     "uk_airports_served": ["LGW", "BRS", "CWL", "LTN"], "other_countries_operated": ["Spain", "Portugal", "Italy", "France"],
     "estimated_annual_spend_gbp_m": 2.1, "estimated_next_review_date": date(2026, 10, 30),
     "is_dcuk_customer": False, "notes": "South of England LCC. Swissport catering."},
    {"name": "Clifton Global", "iata_code": "CG", "type": "full_service", "hq_country": "United Kingdom",
     "uk_airports_served": ["LHR", "BRS"], "other_countries_operated": ["USA", "Canada", "Australia"],
     "estimated_annual_spend_gbp_m": 3.3, "estimated_next_review_date": date(2027, 6, 30),
     "is_dcuk_customer": True, "notes": "Bristol-based full-service. Long-haul focus."},
    {"name": "Elara Airlines", "iata_code": "EL", "type": "full_service", "hq_country": "Japan",
     "uk_airports_served": ["LHR"], "other_countries_operated": ["Japan", "Singapore", "UAE", "USA"],
     "estimated_annual_spend_gbp_m": 4.9, "estimated_next_review_date": date(2027, 9, 1),
     "is_dcuk_customer": False, "notes": "Japanese carrier. Premium service requirements. dnata Group catering in Singapore."},
    {"name": "Osprey Aviation", "iata_code": "OA", "type": "charter", "hq_country": "United Kingdom",
     "uk_airports_served": ["BHX", "MAN", "NCL"], "other_countries_operated": ["Caribbean", "USA"],
     "estimated_annual_spend_gbp_m": 0.6, "estimated_next_review_date": date(2026, 8, 15),
     "is_dcuk_customer": False, "notes": "Long-haul charter specialist."},
    {"name": "Greystone Air", "iata_code": "GR", "type": "low_cost", "hq_country": "Poland",
     "uk_airports_served": ["LTN", "STN", "LGW", "EDI"], "other_countries_operated": ["Poland", "Germany", "Spain"],
     "estimated_annual_spend_gbp_m": 1.7, "estimated_next_review_date": date(2027, 3, 30),
     "is_dcuk_customer": False, "notes": "Eastern European LCC. Growing UK presence."},
    {"name": "Harland Express", "iata_code": "HE", "type": "low_cost", "hq_country": "United Kingdom",
     "uk_airports_served": ["EDI", "GLA", "NCL", "BFS"], "other_countries_operated": ["Spain", "France"],
     "estimated_annual_spend_gbp_m": 0.9, "estimated_next_review_date": date(2027, 1, 15),
     "is_dcuk_customer": False, "notes": "Scottish and Northern Ireland LCC."},
    {"name": "Whitmore Airways", "iata_code": "WA", "type": "full_service", "hq_country": "United Kingdom",
     "uk_airports_served": ["LHR", "MAN", "BHX", "EDI"], "other_countries_operated": ["UAE", "India", "Hong Kong", "Thailand"],
     "estimated_annual_spend_gbp_m": 6.5, "estimated_next_review_date": date(2027, 10, 1),
     "is_dcuk_customer": True, "notes": "Major UK full-service. Key strategic account."},
    {"name": "Farleigh Cargo", "iata_code": "FC", "type": "cargo", "hq_country": "United Kingdom",
     "uk_airports_served": ["LHR", "STN"], "other_countries_operated": ["USA", "UAE"],
     "estimated_annual_spend_gbp_m": 0.2, "estimated_next_review_date": date(2027, 4, 30),
     "is_dcuk_customer": False, "notes": "Small UK cargo operator. Crew meals only."},
]

# Airport presence data: (airline_name, airport, caterer)
AIRPORT_PRESENCE = [
    ("Emerald Skies", "LHR", "dcuk"), ("Emerald Skies", "LGW", "dcuk"), ("Emerald Skies", "MAN", "dcuk"),
    ("Crescent Air", "LHR", "Gate Gourmet"), ("Crescent Air", "MAN", "Gate Gourmet"),
    ("Polar Atlantic", "LHR", "dcuk"), ("Polar Atlantic", "EDI", "dcuk"), ("Polar Atlantic", "MAN", "dcuk"),
    ("Meridian Express", "LHR", "Alpha LSG"), ("Meridian Express", "LGW", "Alpha LSG"), ("Meridian Express", "BHX", "Alpha LSG"), ("Meridian Express", "MAN", "unknown"),
    ("Highland Carrier", "EDI", "dcuk"), ("Highland Carrier", "GLA", "dcuk"), ("Highland Carrier", "MAN", "dcuk"), ("Highland Carrier", "BFS", "dcuk"),
    ("Aurora Air", "LHR", "Alpha LSG"), ("Aurora Air", "MAN", "unknown"),
    ("Cobalt Airlines", "LGW", "dcuk"), ("Cobalt Airlines", "STN", "dcuk"), ("Cobalt Airlines", "LTN", "Gate Gourmet"), ("Cobalt Airlines", "BHX", "dcuk"),
    ("Saffron Express", "LHR", "dcuk"), ("Saffron Express", "BHX", "dcuk"),
    ("Vantage Air", "LHR", "Gate Gourmet"), ("Vantage Air", "MAN", "Gate Gourmet"), ("Vantage Air", "EDI", "unknown"),
    ("Strata Pacific", "LHR", "Alpha LSG"),
    ("Cascade Blue", "STN", "self-catering"), ("Cascade Blue", "LTN", "self-catering"), ("Cascade Blue", "EMA", "self-catering"), ("Cascade Blue", "BRS", "self-catering"),
    ("Solstice Airways", "MAN", "dcuk"), ("Solstice Airways", "BHX", "dcuk"), ("Solstice Airways", "NCL", "dcuk"), ("Solstice Airways", "LPL", "dcuk"),
    ("Thornwick Air", "STN", "Gate Gourmet"), ("Thornwick Air", "LTN", "Gate Gourmet"), ("Thornwick Air", "BFS", "Gate Gourmet"), ("Thornwick Air", "EDI", "Gate Gourmet"), ("Thornwick Air", "GLA", "unknown"),
    ("Marlowe Aviation", "LHR", "dcuk"), ("Marlowe Aviation", "LGW", "dcuk"),
    ("Indigo Route", "LGW", "Gate Gourmet"), ("Indigo Route", "STN", "Gate Gourmet"), ("Indigo Route", "BRS", "Gate Gourmet"),
    ("Fenwick Skies", "BRS", "Alpha LSG"), ("Fenwick Skies", "CWL", "Alpha LSG"), ("Fenwick Skies", "NCL", "Alpha LSG"),
    ("Hadrian Global", "LHR", "dcuk"), ("Hadrian Global", "EDI", "dcuk"), ("Hadrian Global", "MAN", "dcuk"), ("Hadrian Global", "NCL", "dcuk"),
    ("Lakeshore Air", "BHX", "Alpha LSG"), ("Lakeshore Air", "EMA", "Alpha LSG"), ("Lakeshore Air", "LPL", "Alpha LSG"), ("Lakeshore Air", "NCL", "unknown"),
    ("Vesper Airways", "LHR", "Gate Gourmet"),
    ("Redwood Airlines", "LHR", "Alpha LSG"), ("Redwood Airlines", "MAN", "Alpha LSG"),
    ("Summit Express", "LGW", "Gate Gourmet"), ("Summit Express", "LHR", "Gate Gourmet"),
    ("Crest Pacific", "MAN", "dcuk"), ("Crest Pacific", "LGW", "dcuk"), ("Crest Pacific", "BRS", "dcuk"),
    ("Meridian Cargo", "LHR", "unknown"), ("Meridian Cargo", "STN", "unknown"), ("Meridian Cargo", "EMA", "unknown"),
    ("Albatross Air", "LHR", "Alpha LSG"),
    ("Clover Aviation", "BFS", "dcuk"), ("Clover Aviation", "EDI", "dcuk"), ("Clover Aviation", "GLA", "dcuk"), ("Clover Aviation", "BRS", "dcuk"), ("Clover Aviation", "CWL", "dcuk"),
    ("Saltire Air", "EDI", "dcuk"), ("Saltire Air", "GLA", "dcuk"),
    ("Pennine Express", "LPL", "unknown"), ("Pennine Express", "NCL", "unknown"), ("Pennine Express", "EMA", "unknown"), ("Pennine Express", "MAN", "unknown"),
    ("Severn Aviation", "BRS", "Gate Gourmet"), ("Severn Aviation", "CWL", "Gate Gourmet"), ("Severn Aviation", "BHX", "Gate Gourmet"),
    ("Tyne Global", "NCL", "dcuk"), ("Tyne Global", "LHR", "dcuk"), ("Tyne Global", "MAN", "dcuk"),
    ("Kestrel Air", "MAN", "Alpha LSG"), ("Kestrel Air", "BHX", "Alpha LSG"), ("Kestrel Air", "EMA", "Alpha LSG"), ("Kestrel Air", "LPL", "Alpha LSG"),
    ("Brunswick Airways", "LHR", "Alpha LSG"), ("Brunswick Airways", "MAN", "Alpha LSG"), ("Brunswick Airways", "BHX", "unknown"),
    ("Montane Cargo", "LHR", "unknown"), ("Montane Cargo", "EMA", "unknown"), ("Montane Cargo", "STN", "unknown"),
    ("Selbourne Air", "LGW", "Swissport"), ("Selbourne Air", "BRS", "Swissport"), ("Selbourne Air", "CWL", "Swissport"), ("Selbourne Air", "LTN", "Swissport"),
    ("Clifton Global", "LHR", "dcuk"), ("Clifton Global", "BRS", "dcuk"),
    ("Elara Airlines", "LHR", "Gate Gourmet"),
    ("Osprey Aviation", "BHX", "Alpha LSG"), ("Osprey Aviation", "MAN", "Alpha LSG"), ("Osprey Aviation", "NCL", "unknown"),
    ("Greystone Air", "LTN", "Gate Gourmet"), ("Greystone Air", "STN", "Gate Gourmet"), ("Greystone Air", "LGW", "Gate Gourmet"), ("Greystone Air", "EDI", "unknown"),
    ("Harland Express", "EDI", "unknown"), ("Harland Express", "GLA", "unknown"), ("Harland Express", "NCL", "unknown"), ("Harland Express", "BFS", "unknown"),
    ("Whitmore Airways", "LHR", "dcuk"), ("Whitmore Airways", "MAN", "dcuk"), ("Whitmore Airways", "BHX", "dcuk"), ("Whitmore Airways", "EDI", "dcuk"),
    ("Farleigh Cargo", "LHR", "unknown"), ("Farleigh Cargo", "STN", "unknown"),
]


def seed_airlines(db):
    from app.models.airline import Airline, AirportPresence
    if db.query(Airline).count() > 0:
        return

    airline_map = {}
    for a in AIRLINES:
        obj = Airline(is_illustrative=True, **a)
        db.add(obj)
        db.flush()
        airline_map[a["name"]] = obj.id

    for airline_name, airport, caterer in AIRPORT_PRESENCE:
        db.add(AirportPresence(
            airline_id=airline_map[airline_name],
            airport_code=airport,
            current_caterer=caterer,
            is_dcuk=(caterer == "dcuk"),
        ))

    db.commit()
    print(f"  Seeded {len(AIRLINES)} airlines and {len(AIRPORT_PRESENCE)} airport presence records")
