"""Seed 25 historical tender outcomes. Idempotent."""
from datetime import date


HISTORICAL = [
    # Won (8)
    {"customer_name": "Hadrian Global", "airline_type": "full_service", "contract_value_gbp": 3800000,
     "submission_date": date(2024, 3, 12), "outcome_date": date(2024, 4, 8), "outcome": "won",
     "contract_length_years": 3.0, "airports_covered": "LHR, EDI, MAN",
     "won_lost_reason": "Competitive pricing and strong culinary proposition. ACS won on value and service quality."},
    {"customer_name": "Solstice Airways", "airline_type": "charter", "contract_value_gbp": 980000,
     "submission_date": date(2024, 5, 20), "outcome_date": date(2024, 6, 15), "outcome": "won",
     "contract_length_years": 2.0, "airports_covered": "MAN, BHX, NCL",
     "won_lost_reason": "Only compliant bidder for seasonal peak requirements. Strong operational proposal."},
    {"customer_name": "Marlowe Aviation", "airline_type": "full_service", "contract_value_gbp": 4100000,
     "submission_date": date(2024, 7, 8), "outcome_date": date(2024, 8, 2), "outcome": "won",
     "contract_length_years": 5.0, "airports_covered": "LHR, LGW",
     "won_lost_reason": "Premium culinary proposition differentiated ACS. Price within 3% of lowest bid."},
    {"customer_name": "Cobalt Airlines", "airline_type": "low_cost", "contract_value_gbp": 2200000,
     "submission_date": date(2024, 9, 15), "outcome_date": date(2024, 10, 10), "outcome": "won",
     "contract_length_years": 3.0, "airports_covered": "LGW, STN, BHX",
     "won_lost_reason": "Cost competitiveness and operational reliability record. Renewal from existing contract."},
    {"customer_name": "Tyne Global", "airline_type": "full_service", "contract_value_gbp": 1600000,
     "submission_date": date(2024, 11, 5), "outcome_date": date(2024, 12, 1), "outcome": "won",
     "contract_length_years": 2.0, "airports_covered": "NCL, LHR",
     "won_lost_reason": "NCL proximity advantage. Strong local operational team cited by customer."},
    {"customer_name": "Crest Pacific", "airline_type": "charter", "contract_value_gbp": 720000,
     "submission_date": date(2025, 2, 18), "outcome_date": date(2025, 3, 10), "outcome": "won",
     "contract_length_years": 2.0, "airports_covered": "MAN, LGW",
     "won_lost_reason": "Specialist long-haul charter capability. Caribbean route expertise."},
    {"customer_name": "Clifton Global", "airline_type": "full_service", "contract_value_gbp": 2900000,
     "submission_date": date(2025, 5, 12), "outcome_date": date(2025, 6, 8), "outcome": "won",
     "contract_length_years": 3.0, "airports_covered": "LHR, BRS",
     "won_lost_reason": "Competitive pricing with strong sustainability credentials. BRS local presence decisive."},
    {"customer_name": "Whitmore Airways", "airline_type": "full_service", "contract_value_gbp": 5200000,
     "submission_date": date(2025, 9, 20), "outcome_date": date(2025, 10, 18), "outcome": "won",
     "contract_length_years": 5.0, "airports_covered": "LHR, MAN, BHX, EDI",
     "won_lost_reason": "Strategic partnership. Multi-airport solution with integrated supply chain."},

    # Lost (12)
    {"customer_name": "Vantage Air", "airline_type": "full_service", "contract_value_gbp": 5400000,
     "submission_date": date(2024, 2, 28), "outcome_date": date(2024, 3, 25), "outcome": "lost",
     "lost_stage": "final_negotiation", "airports_covered": "LHR, MAN",
     "won_lost_reason": "Lost on price. Gate Gourmet underbid by 12%. Margin floor prevented match."},
    {"customer_name": "Thornwick Air", "airline_type": "low_cost", "contract_value_gbp": 1800000,
     "submission_date": date(2024, 4, 10), "outcome_date": date(2024, 5, 5), "outcome": "lost",
     "lost_stage": "shortlist", "airports_covered": "STN, LTN",
     "won_lost_reason": "Not shortlisted. Submission submitted 2 days late due to internal process failure."},
    {"customer_name": "Aurora Air", "airline_type": "full_service", "contract_value_gbp": 2100000,
     "submission_date": date(2024, 6, 22), "outcome_date": date(2024, 7, 18), "outcome": "lost",
     "lost_stage": "final_evaluation", "airports_covered": "LHR",
     "won_lost_reason": "Lost to Alpha LSG. Customer cited stronger premium cabin culinary proposition from competitor."},
    {"customer_name": "Greystone Air", "airline_type": "low_cost", "contract_value_gbp": 1400000,
     "submission_date": date(2024, 8, 15), "outcome_date": date(2024, 9, 10), "outcome": "lost",
     "lost_stage": "shortlist", "airports_covered": "LTN, STN",
     "won_lost_reason": "Gate Gourmet maintained incumbent position. ACS could not match price on low-margin LCC contract."},
    {"customer_name": "Selbourne Air", "airline_type": "low_cost", "contract_value_gbp": 1600000,
     "submission_date": date(2024, 10, 8), "outcome_date": date(2024, 11, 2), "outcome": "lost",
     "lost_stage": "final_negotiation", "airports_covered": "LGW, BRS",
     "won_lost_reason": "Swissport retained on price. Customer did not value premium service differentiator."},
    {"customer_name": "Elara Airlines", "airline_type": "full_service", "contract_value_gbp": 4600000,
     "submission_date": date(2024, 11, 25), "outcome_date": date(2024, 12, 20), "outcome": "lost",
     "lost_stage": "final_evaluation", "airports_covered": "LHR",
     "won_lost_reason": "Gate Gourmet won on culinary proposition for Japanese carrier. Specialist requirements underestimated."},
    {"customer_name": "Brunswick Airways", "airline_type": "full_service", "contract_value_gbp": 5100000,
     "submission_date": date(2025, 1, 15), "outcome_date": date(2025, 2, 10), "outcome": "lost",
     "lost_stage": "shortlist", "airports_covered": "LHR, MAN",
     "won_lost_reason": "Not shortlisted. Alpha LSG Group relationship in Germany was decisive factor."},
    {"customer_name": "Indigo Route", "airline_type": "low_cost", "contract_value_gbp": 1200000,
     "submission_date": date(2025, 3, 20), "outcome_date": date(2025, 4, 15), "outcome": "lost",
     "lost_stage": "final_evaluation", "airports_covered": "LGW, STN",
     "won_lost_reason": "Gate Gourmet incumbent retained. Buy-on-board model favoured existing logistics integration."},
    {"customer_name": "Strata Pacific", "airline_type": "full_service", "contract_value_gbp": 4200000,
     "submission_date": date(2025, 6, 10), "outcome_date": date(2025, 7, 5), "outcome": "lost",
     "lost_stage": "final_negotiation", "airports_covered": "LHR",
     "won_lost_reason": "Alpha LSG won. Premium long-haul proposition gap. Customer required more bespoke culinary development."},
    {"customer_name": "Redwood Airlines", "airline_type": "full_service", "contract_value_gbp": 3800000,
     "submission_date": date(2025, 8, 8), "outcome_date": date(2025, 9, 2), "outcome": "lost",
     "lost_stage": "shortlist", "airports_covered": "LHR, MAN",
     "won_lost_reason": "Submission quality issues. MPL inconsistencies flagged by customer. Internal process error."},
    {"customer_name": "Cascade Blue", "airline_type": "low_cost", "contract_value_gbp": 1500000,
     "submission_date": date(2025, 10, 20), "outcome_date": date(2025, 11, 14), "outcome": "lost",
     "lost_stage": "final_evaluation", "airports_covered": "STN, LTN, BRS",
     "won_lost_reason": "Customer chose to continue self-catering. Outsource business case not compelling enough."},
    {"customer_name": "Kestrel Air", "airline_type": "charter", "contract_value_gbp": 680000,
     "submission_date": date(2025, 12, 5), "outcome_date": date(2026, 1, 8), "outcome": "lost",
     "lost_stage": "final_negotiation", "airports_covered": "MAN, BHX",
     "won_lost_reason": "Alpha LSG matched on price and had existing kitchen infrastructure at BHX."},
    {"customer_name": "Pennine Express", "airline_type": "low_cost", "contract_value_gbp": 900000,
     "submission_date": date(2026, 2, 14), "outcome_date": date(2026, 3, 10), "outcome": "lost",
     "lost_stage": "shortlist", "airports_covered": "LPL, NCL, EMA",
     "won_lost_reason": "No ACS kitchen presence at LPL or EMA. Logistics cost made bid uncompetitive."},

    # Withdrawn (5)
    {"customer_name": "Vesper Airways", "airline_type": "full_service", "contract_value_gbp": 5600000,
     "submission_date": None, "outcome_date": date(2024, 5, 1), "outcome": "withdrawn",
     "lost_stage": None, "airports_covered": "LHR",
     "won_lost_reason": "Withdrawn at DTP stage. ET Go/No-Go was No-Go. Margin requirements not viable at customer's expected price point."},
    {"customer_name": "Fenwick Skies", "airline_type": "charter", "contract_value_gbp": 480000,
     "submission_date": None, "outcome_date": date(2024, 9, 15), "outcome": "withdrawn",
     "lost_stage": None, "airports_covered": "BRS, NCL",
     "won_lost_reason": "Withdrawn at strategy stage. Customer timeline incompatible with mobilisation requirements."},
    {"customer_name": "Osprey Aviation", "airline_type": "charter", "contract_value_gbp": 560000,
     "submission_date": None, "outcome_date": date(2025, 4, 8), "outcome": "withdrawn",
     "lost_stage": None, "airports_covered": "BHX, MAN",
     "won_lost_reason": "Withdrawn post-DTP. ET decision No-Go. Contract terms contained unacceptable liability provisions."},
    {"customer_name": "Summit Express", "airline_type": "low_cost", "contract_value_gbp": 980000,
     "submission_date": None, "outcome_date": date(2025, 7, 22), "outcome": "withdrawn",
     "lost_stage": None, "airports_covered": "LGW",
     "won_lost_reason": "Withdrawn at requirements stage. Customer changed scope mid-process making submission unviable."},
    {"customer_name": "Harland Express", "airline_type": "low_cost", "contract_value_gbp": 720000,
     "submission_date": None, "outcome_date": date(2026, 1, 20), "outcome": "withdrawn",
     "lost_stage": None, "airports_covered": "EDI, GLA",
     "won_lost_reason": "Withdrawn. Customer withdrew from market — internal restructuring."},
]


def seed_historical_tenders(db):
    from app.models.historical import HistoricalTender
    if db.query(HistoricalTender).count() > 0:
        return
    for h in HISTORICAL:
        db.add(HistoricalTender(**h))
    db.commit()
    print(f"  Seeded {len(HISTORICAL)} historical tender records")
